### ISSUE TITLE
on('ready') is fired before page is ready (self.pageReady == false)

### ISSUE THREAD

**Issue by avatarkava** [atomjack/dubtrackapi#10]
Referenced in https://github.com/atomjack/dubtrackapi/issues/8 comments as well.

Can replicate by calling any DubtrackAPI function (like `getEvents`) immediately inside the `on('ready')` listener.  Function kicks back out at the check for `self.pageReady === false`.

**Comment by atomjack** [comment]
I'll also note that this commit removes the emission of 'djAdvance' - you should use 'room_playlist-update' instead.
