### ISSUE TITLE
Song Advancement Failing

### ISSUE THREAD

**Issue by jcott28** [atomjack/dubtrackapi#16]
Every time a new track starts (youtube at least).... I get this error which crashes the bot.  I tried pulling a fresh install to make sure my changes didn't mess it up.  So this is happening with a fresh pull from git.
I'm on Ubuntu 14.04

Not sure if the changes they're slowly pushing out with the new UI are affecting things.  Im guessing it has to do with the fact that phantom can't process HTML5 so the video player is undefined?

Got an error from the virtual browser:  TypeError: undefined is not a function (evaluating 'this.player.loadVideoById') [ { file: 'https://mediadubtrackfm.s3.amazonaws.com/assets/js/dubtrack.min.js?v=13232234326609712',
    line: 7,
    function: 'loadVideo' },
  { file: 'https://mediadubtrackfm.s3.amazonaws.com/assets/js/dubtrack.min.js?v=13232234326609712',
    line: 7,
    function: 'buildYT' },
  { file: 'https://mediadubtrackfm.s3.amazonaws.com/assets/js/dubtrack.min.js?v=13232234326609712',
    line: 7,
    function: 'render' },
  { file: 'https://mediadubtrackfm.s3.amazonaws.com/assets/js/dubtrack.min.js?v=13232234326609712',
    line: 7,
    function: 'realTimeUpdate' },
  { file: 'https://mediadubtrackfm.s3.amazonaws.com/assets/js/includes.min.js?v=13232234326609712',
    line: 13,
    function: 'l' },
  { file: 'https://mediadubtrackfm.s3.amazonaws.com/assets/js/includes.min.js?v=13232234326609712',
    line: 13,
    function: 'trigger' },
  { file: 'https://mediadubtrackfm.s3.amazonaws.com/assets/js/dubtrack.min.js?v=13232234326609712',
    line: 2,
    function: 'callback' },
  { file: 'https://mediadubtrackfm.s3.amazonaws.com/assets/js/dubtrack.min.js?v=13232234326609712',
    line: 2,
    function: 'callback' },
  { file: 'https://cdn.pubnub.com/pubnub.min.js',
    line: 81,
    function: '' },
  { file: 'https://cdn.pubnub.com/pubnub.min.js',
    line: 35,
    function: 'N' },
  { file: 'https://cdn.pubnub.com/pubnub.min.js',
    line: 81,
    function: 'c' },
  { file: 'https://cdn.pubnub.com/pubnub.min.js',
    line: 59,
    function: 'f' } ]
...

**Comment by ImGrumpy** [comment]
Duplicate of issue https://github.com/atomjack/dubtrackapi/issues/14 (before it was hijacked).

**Comment by jcott28** [comment]
Crap, I had though #14 was for Soundcloud only. The soundcloud issue is a different ticket. Thanks.
