### ISSUE TITLE
Installation Failing

### ISSUE THREAD

**Issue by jcott28** [atomjack/dubtrackapi#2]
Sorry if this is stupid, but perhaps you've seen the issue.

I have downloaded the latest index.jsp file you have here.  I have node installed (I've tried 4 and 0.10.7 just in case it needed to be an older version), phantomjs installed (on Debian) : v 2.0.0.   I have phantom installed via npm install (v0.8.0).

But if I try to run the dubtrackapi, I just get this error:

```
[voltron ~/bot] phantomjs dubtrackapi.js
Error: Cannot find module 'events'

  phantomjs://bootstrap.js:299 in require
  phantomjs://bootstrap.js:263 in require
  :1
Error: Cannot find module 'stream'

  phantomjs://bootstrap.js:299 in require
  phantomjs://bootstrap.js:263 in require
  :2
Error: Cannot find module 'net'

  phantomjs://bootstrap.js:299 in require
  phantomjs://bootstrap.js:263 in require
  :3
Error: Cannot find module 'http'

  phantomjs://bootstrap.js:299 in require
  phantomjs://bootstrap.js:263 in require
  :8
  :193
Error: Cannot find module 'events'

  phantomjs://bootstrap.js:299 in require
  phantomjs://bootstrap.js:263 in require
  dubtrackapi.js:4
^C
[voltron ~/bot]
```

If you have any insight, I would really appreciate it.  Ran into the problem on both my Windows box and Debian.
Thanks!

**Comment by atomjack** [comment]
Ok, you need to install phantomjs-node: 

`npm install phantom`

And you run your script with node, not with phantomjs.

**Comment by jcott28** [comment]
Oh man, now I feel like an idiot.  I had phantomjs-node installed, but I was running it with phantomjs. Thanks!
