### ISSUE TITLE
addCookie error

### ISSUE THREAD

**Issue by jtrutwin-zz** [atomjack/dubtrackapi#5]
this line in dubtrackapi/index.js appears to be causing an error:

```
    self.ph.addCookie('connect.sid', self.creds, '.dubtrack.fm');
```

phantom stdout: Error: incompatible type of argument(s) in call to addCookie(); candidates were
    addCookie(QVariantMap)

phantom stdout:   /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:9590 in addCookie
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:9590 in addCookie
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:6075 in apply
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:6051 in handle
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:5936 in handle
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:5924 in write
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:4778 in ondata
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:1747 in emit
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:6670 in onmessage
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:6766 in dispatchEvent
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:7675 in _dispatchMessage
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:7733 in _didMessage
  /net/home/test_accounts/rhel7test4/bot/node_modules/phantom/shim.js:7865 in onmessage

This is on a fresh install.  It appears the cookie function in phantom's shim.js is looking for different kinds of parameters than are being passed by dubtrackapi?

  addCookie: function(cookie, cb) {
    if (cb == null) {
      cb = function() {};
    }
    return cb(phantom.addCookie(cookie));
  },

**Comment by atomjack** [comment]
Yeah, I started getting that all of a sudden as well. I think phantom-nodejs version 0.7.2 wants you to pass strings to addCookie, while 0.8.0 wants an object. I know for plugbotapi, I had been passing it an object, but when I started on this API it wasn't working until I passed it strings, but maybe I had somehow had 0.7.2 installed. I recently upgraded to 0.8.0 and it started throwing that error, so I changed it to pass an object to addCookie, and it worked again. I'll update the API to require phantom 0.8.0 and pass the object, and that should hopefully work. I just haven't had the time to examine the issue further. Stand by and I'll push up a fix.

**Comment by jtrutwin-zz** [comment]
Thanks - no rush, happy with whenever you can get to.  If I was a little better at JS I'd submit a patch myself...

**Comment by atomjack** [comment]
Please give that a try and let me know if it works.

**Comment by jtrutwin-zz** [comment]
works like a champ - thanks for the help!
