### ISSUE TITLE
[Offtopic] Can't install phantomJS 2(.0)

### ISSUE THREAD

**Issue by Plateam** [atomjack/dubtrackapi#6]
node testbot.js
connecting to fautors-lobby
connecting to fautors-lobby
Sorry, but PlugBotAPI requires phantomjs version >= 2.0.0. You are running version 1.9.8.

I'm tried at least 10-15 differrent methods to install v2.x on (Ubuntu) linux. It simply can't.

Which means that do i really have to wait next release?? (npm install phantomjs2 = error error error)

Any suggestion, can i install phantomJS2 _succesfully_ on Ubuntu linux?

If so, where?

**Comment by jtrutwin-zz** [comment]
Assuming the Ubuntu version is pretty recent I would assume these instructions would work for you:

http://phantomjs.org/build.html

I was able to build it under both RHEL 6 and 7 without any issues.  Are you getting a compiler error on ubuntu?

good luck.

**Comment by atomjack** [comment]
You can try the 2.0 binary I use on Ubuntu that I compiled: https://www.dropbox.com/s/3j8vmnayhwhv8m9/phantomjs2.0.gz?dl=0

**Comment by Plateam** [comment]
jtrutwin: 14.04 LTS. 
I tried that one also. But now i try to remove phantom and then do that.

atomjack: /usr/bin xDD Sorry i'm newbie in this

**Comment by atomjack** [comment]
@Plateam more info? Put that binary in /usr/local/bin, make sure to chmod +x it, and then run it. It probably will complain about missing libraries, so you will have to install them (with apt-get). Just look up the name of the .so or whatever in google, and figure out which packages you need to install.

**Comment by Plateam** [comment]
node testbot.js
connecting to fautors-lobby
connecting to fautors-lobby
opening page
phantom stdout: Error: incompatible type of argument(s) in call to addCookie(); candidates were
    addCookie(QVariantMap)

phantom stdout:   /home/toni/node_modules/phantom/shim.js:9590 in addCookie
  /home/toni/node_modules/phantom/shim.js:9590 in addCookie
  /home/toni/node_modules/phantom/shim.js:6075 in apply
  /home/toni/node_modules/phantom/shim.js:6051 in handle
  /home/toni/node_modules/phantom/shim.js:5936 in handle
  /home/toni/node_modules/phantom/shim.js:5924 in write
  /home/toni/node_modules/phantom/shim.js:4778 in ondata
  /home/toni/node_modules/phantom/shim.js:1747 in emit
  /home/toni/node_modules/phantom/shim.js:6670 in onmessage
  /home/toni/node_modules/phantom/shim.js:6766 in dispatchEvent
  /home/toni/node_modules/phantom/shim.js:7675 in _dispatchMessage
  /home/toni/node_modules/phantom/shim.js:7733 in _didMessage
  /home/toni/node_modules/phantom/shim.js:7865 in onmessage

Pfft.

**Comment by atomjack** [comment]
@Plateam See #5

**Comment by Plateam** [comment]
@atomjack Thank you.

node testbot.js
connecting to fautors-lobby
connecting to fautors-lobby
opening page
status:  success

There's only one problem:

I can't see bot at dubtrack.

Should i
1. open AND login with browser, then run node or
2. open but do not login then run node or
3. Do not open and logout if logged in and then run node or
4. other or
5. This is dubtrack problem.

**Comment by atomjack** [comment]
@Plateam The only thing you need to use your browser for is to get the value of the connect.sid cookie so that your bot can login under that account.

Is your bot emitting the 'ready' event? Or the 'chat' event? Please post your bot's code (without the cookie of course).

**Comment by Plateam** [comment]
@atomjack It doesn't have anything functions more. 

I tried to test that does it connect. No.

Which means that the code looks like this: 

var DubtrackAPI = require('./dubtrackapi');
var creds = 'This_is_something_random'; // Put the value of the connect.sid cookie here

var bot = new DubtrackAPI(creds);

bot.connect('fautors-lobby'); // specify the room name part of the url for the room

bot.on('ready', function(data) {
  console.log("Ready to go: ", data);
  // data contains the currentDJ (by name) and currentTrack (artist and track), and the list of users in the room (does not update on join/depart)
});

bot.on('chat-message', function(data) {
  console.log("got chat: ", data);
});

bot.on('djAdvance', function(data) {
  console.log("new song playing: ", data);
});

/*
bot.getEvents(function(events) {
  console.log("These are the Dubtrack events I respond to: ", events);
}); */

i know my connect.sid and it is in creds.

**Comment by atomjack** [comment]
Only thing I can think of is that it's not actually logging in. Could your connect.sid cookie value be bad? Maybe try logging in as the bot's account again and get the value, it might change if you have logged in manually as that account since you first got it.

**Comment by Plateam** [comment]
@atomjack Succes!

I removed connect.sid cookie from my computer from browser settings. Then logged in and found it again. Now it's connected fine. Next, i try to grab 'command here' from chat messages and then bot to react. 

Edit: Tomorrow project. _Sleeping_

**Comment by atomjack** [comment]
Awesome. I had the same problem and had to redo my cookie value. I also was still having problems with the bot starting up properly and realized I had been injecting a js library into the virtual browser that I had initially tried to use to monitor new tracks starting, and that fixed the problem. Pushed that up.

Also, I just noticed that you can now login with a username and password, although there doesn't appear to be a way to link an account already created with twitter or facebook with one that you can login that way as. Once that happens I will update the API to use that as the login method instead of the cookie.

**Comment by Plateam** [comment]
Thank you all!

Edit: command !test working fine ^^
