### ISSUE TITLE
Cannot connect with newest version of API

### ISSUE THREAD

**Issue by ImGrumpy** [atomjack/dubtrackapi#8]
When trying to connect using the cookie, I get:

```
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at DubtrackAPI.emit (events.js:74:15)
    at C:\bots\lilbuddy (dubtrack)\node_modules\dubtrackapi\index.js:157:16
```

With email/password creds instead, I get:

```
TypeError: Cannot read property 'state' of null
    at C:\bots\lilbuddy (dubtrack)\node_modules\dubtrackapi\index.js:81:20
```

Old version of the API connects and logs like it's working fine - it sees events - but doesn't respond to chat.  Sort of feels like it's in guest mode, but not sure.  Tried updating the cookie creds with no luck.

**Comment by ImGrumpy** [comment]
Researching a little more, I find that phantom is failing opening the login page when using the user/pass creds, still no idea why though.

**Comment by atomjack** [comment]
For the unspecified "error" event error, make sure your bot is responding to the error event:

```
bot.on('error', function(msg, trace) {

});
```

I'll have to do some research to figure out why that is required.

And I'll have to do some more work on the user/password login, I thought I had that working.

**Comment by ImGrumpy** [comment]
Ok, adding the error event to the code and logging the error gave me this 10x then dropped out:

``````
ReferenceError: Can't find variable: $
[{"file":"phantomjs://webpage.evaluate()","line":11,"function":""}]```

``````

**Comment by atomjack** [comment]
Post your bot's source?

**Comment by ImGrumpy** [comment]
Any particular pieces?  Honestly, it's 2000 lines long (lots of Plug leftovers) and I don't want to share it's source.  It was working Friday...

**Comment by atomjack** [comment]
Hmmm not sure, does it do that over and over? I also just pushed up a change that fixes the hardcoded room when using username and password (but I haven't had time to research any login problems yet), and also it now prevents the need to catch the error event, so maybe that might help?

**Comment by ImGrumpy** [comment]
No change, except now it loops endlessly instead of failing after 10x.  It honestly is acting like Phantom can't open the page.  Not sure if this may be a Windows vs *nix thing?

**Comment by atomjack** [comment]
What if you do a really simple bot like in the example?

**Comment by ImGrumpy** [comment]
ok, copied the test code exactly (except for the credentials and the room name obviously).  Received this, then it hung:

```
C:\bots\lilbuddy (dubtrack)>node test.js
phantom stdout: ReferenceError: Can't find variable: $

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():5

phantom stdout: ReferenceError: Can't find variable: $

  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():9

```

**Comment by ImGrumpy** [comment]
Ok first attempt of that was with user/pass creds.  With the cookie creds I get this over and over:

```
Got an error from the virtual browser:  ReferenceError: Can't find variable: $ [
 { file: 'phantomjs://webpage.evaluate()',
    line: 11,
    function: '' } ]
```

**Comment by atomjack** [comment]
Is it possible you are doing something like bot.chat or bot.getEvents before the bot emits the 'ready' event?

**Comment by ImGrumpy** [comment]
Not when just copying your sample code.

**Comment by atomjack** [comment]
Not what? Please elaborate.

**Comment by ImGrumpy** [comment]
I meant even if my bot was accidentally doing that, the test one I just made using your demo code from the readme certainly isn't.

**Comment by Plateam** [comment]
[Joining discussion]

[Current code is 98% copy-paste from README.md, right?]
[Only creds and room name different]

**Comment by ImGrumpy** [comment]
Right.

**Comment by ImGrumpy** [comment]
The only thing I can add here is that if I add a `page.render` after the room's `page.open` command, with Friday's API I get a dubtrack screenshot and with today's API I get a black screen.

**Comment by ImGrumpy** [comment]
Ok, got it working with user/pass creds, but I'll need you to decipher why.  Something about this [commit](https://github.com/atomjack/dubtrackapi/commit/15eb5ac151b09dbc6945dc01431a41f5a9571d4e) caused a problem.  When I undid the new createPage code:

```
      var self = this;
      phantom.create(function(ph) {
```

and replaced with the older code:

```
      var self = this;
      var phantomOptions = {
        port: self.phantomPort,
        'ignore-ssl-errors': 'yes'
      };
      phantom.create("--ssl-protocol=TLSv1", phantomOptions, function(ph) {
```

I was able to login correctly, bot is working again.

**Comment by atomjack** [comment]
Ahhhh woops. Well, you're welcome to fork and put that back in if you want :)

**Comment by ImGrumpy** [comment]
I wish I could figure that forking stuff out, no luck so far, sorry.  When I fell a branch behind, I had no idea how to update it.  I also have no idea _why_ my fix here works, which means I'd feel pretty funny about making a pull request for it.

**Comment by ImGrumpy** [comment]
Closing this.  I did a clean install of all my old modules and this problem went away without need to modify the code.
